apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: exchange-listener
spec:
  type: LoadBalancer
  ports:
  # Порт внутреннего сетевого балансировщика, на котором будут
  # обслуживаться пользовательские запросы.
  - port: 5672
    name: amqp-port
    # Порт контейнера, на котором доступно приложение.
    targetPort: 5672
  - port: 15672
    name: http-stats-port
    targetPort: 15672
  # Метки селектора, использованные в шаблоне подов при создании
  # объекта Deployment.
  selector:
    app.kubernetes.io/name: rabbitmq
