name: elistener-yandex
version: 1.0.0
description: exchange-listener for yandex cloud
maintainers:
  - name: Nikolay Krasnov
    email: nkrasnov@nobilis.team
appVersion: 1.0

dependencies:

  - name: exchangelistener
    version: "0.8.74"
    repository: "file://exchangelistener"
...
