apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  labels:
    app: rabbitmq
  name: rabbitmq
  namespace: exchange-listener
spec:
  affinity:
     nodeAffinity:
       requiredDuringSchedulingIgnoredDuringExecution:
         nodeSelectorTerms:
         - matchExpressions:
           - key: kubernetes.io/hostname
             operator: In
             values:
             - k8sm00
             - k8sm01
             - k8sm02
             - k8sw00
  replicas: 3
  image: rabbitmq:3.11.6
  service:
    type: ClusterIP
  persistence:
    storageClassName: fast-disks
    storage: 9978Mi
  resources:
    requests:
      cpu: 256m
      memory: 1Gi
    limits:
      cpu: 256m
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
                 log.console.level = info
                 channel_max = 1700
                 default_user_tags.administrator = true
    advancedConfig: ""
