{{- if (eq (include "rabbitmq.enabled" .) "true") }}
apiVersion: {{ .Values.apiVersion }}
kind: Deployment
metadata:
  name: {{ .Release.Name }}-worker
spec:
  selector:
    matchLabels:
      app: {{ include "base-service.name" . }}-worker
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.workerReplicaCount }}
  template:
    metadata:
      labels:
{{ include "labels" (dict "root" . "prefix" "worker") | indent 8 }}
      annotations:
        prometheus.io/scrape: "true"
    spec:
      volumes:
        - name: log4net-exchange-listeners
          configMap:
            name: {{ .Release.Name }}-log4net
            items:
              - key: log4net.config
                path: log4net.config
        - name: appsettings-exchange-listeners
          configMap:
            name: {{ .Release.Name }}-appsettings
            items:
              - key: appSettings
                path: appsettings.json
        - name: rabbitmq-exchange-listeners
          secret:
            secretName: {{ include "rabbitmq.secretName" . }}
            items:
              - key: appSettings
                path: appsettings.Production.json
      containers:
        - name: {{ .Chart.Name }}
{{- if (not (empty .Values.workerImage)) }}
          image: "{{ .Values.workerImage.repository }}:{{ .Values.workerImage.tag | default .Values.image.tag }}"
          imagePullPolicy: {{ .Values.workerImage.pullPolicy | default .Values.image.pullPolicy }}
{{- else }}
          image: "{{ .Values.image.repository }}-worker:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
{{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /liveness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          readinessProbe:
            httpGet:
              path: /readiness
              port: http
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 60
            successThreshold: 1
            failureThreshold: 10
          resources:
            limits:
              memory: {{ .Values.resources.worker.limits.memory }}
              cpu: {{ .Values.resources.worker.limits.cpu }}
            requests:
              memory: 800Mi
              cpu: 100m
          volumeMounts: 
            - name: log4net-exchange-listeners
              mountPath: {{ include "log4net.mountPath" . }}
              subPath: log4net.config
            - name: appsettings-exchange-listeners
              mountPath: /app/appsettings.json
              subPath: appsettings.json
            - name: rabbitmq-exchange-listeners
              mountPath: /app/appsettings.Production.json
              subPath: appsettings.Production.json
          env:
            - name: Log4NetPath
              value: {{ include "log4net.mountPath" . }}
            - name: ExchangeListenerRedisHost
              value: "{{ .Values.env.host }}:{{ .Values.env.port }}"
            - name: ExchangeListenerRedisDatabase
              value: "{{ .Values.env.base }}"
{{- range $key, $val := .Values.env }}
{{- if (and (ne $key "base") (ne $key "host") (ne $key "port")) }}
            - name: {{ $key }}
              value: {{ $val | quote }}
{{- end }}
    {{- end }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
{{- end }}
