{{- $rabbitmqEnabled := eq (include "rabbitmq.enabled" .) "true" -}}
{{- if (include "rabbitmq.shouldCreateSecret" .) }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ include "rabbitmq.secretName" . }}
type: Opaque
stringData:
  appSettings: |
    {
{{- if $rabbitmqEnabled }}
      "ConnectionStrings": {
        "RabbitMQ": "{{ include "rabbitmq.connectionString" . }}"
      },
      "RabbitMQSettings": {
        "Login": "{{ .Values.RabbitMQ.Login }}",
        "Password": "{{ .Values.RabbitMQ.Password }}",
      }
{{- end }}
    }
{{- end }}