apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  name: {{ .Release.Name }}-api
  labels:
{{include "labels" (dict "root" . "prefix" "api" ) | indent 4}}
spec:
  type: {{ .Values.service.type }}
  {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.externalTrafficPolicy))) }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if (and (eq .Values.service.type "NodePort") (not (empty .Values.service.nodePort))) }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
  selector:
    app: {{ include "base-service.name" . }}-api
    app.kubernetes.io/instance: {{ .Release.Name }}
