---
# Source: local-volume-static-provisioner/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: local-storage-admin
  namespace: local-pv
  labels:
    helm.sh/chart: local-volume-static-provisioner-1.0.0
    app.kubernetes.io/name: local-volume-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: localpv
---
# Source: local-volume-static-provisioner/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: localpv-local-volume-static-provisioner-config
  namespace: local-pv
  labels:
    helm.sh/chart: local-volume-static-provisioner-1.0.0
    app.kubernetes.io/name: local-volume-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: localpv
data:
  labelsForPV: |
    pv-labels : can-be-selected
  storageClassMap: |
    fast-disks:
      hostDir: /hdd
      mountDir: /hdd
      blockCleanerCommand:
        - "/scripts/shred.sh"
        - "2"
      volumeMode: Filesystem
      fsType: ext4
      namePattern: "*"
---
# Source: local-volume-static-provisioner/templates/storageclass.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: fast-disks
  labels:
    helm.sh/chart: local-volume-static-provisioner-1.0.0
    app.kubernetes.io/name: local-volume-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: localpv
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
---
# Source: local-volume-static-provisioner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: localpv-local-volume-static-provisioner-node-clusterrole
  labels:
    helm.sh/chart: local-volume-static-provisioner-1.0.0
    app.kubernetes.io/name: local-volume-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: localpv
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["storage.k8s.io"]
  resources: ["storageclasses"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["watch"]
- apiGroups: ["", "events.k8s.io"]
  resources: ["events"]
  verbs: ["create", "update", "patch"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get"]
---
# Source: local-volume-static-provisioner/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: localpv-local-volume-static-provisioner-node-binding
  labels:
    helm.sh/chart: local-volume-static-provisioner-1.0.0
    app.kubernetes.io/name: local-volume-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: localpv
subjects:
- kind: ServiceAccount
  name: local-storage-admin
  namespace: local-pv
roleRef:
  kind: ClusterRole
  name: localpv-local-volume-static-provisioner-node-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
# Source: local-volume-static-provisioner/templates/daemonset_linux.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: localpv-local-volume-static-provisioner
  namespace: local-pv
  labels:
    helm.sh/chart: local-volume-static-provisioner-1.0.0
    app.kubernetes.io/name: local-volume-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: localpv
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: local-volume-static-provisioner
      app.kubernetes.io/instance: localpv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-volume-static-provisioner
        app.kubernetes.io/instance: localpv
      annotations:
        checksum/config: d64a1ddfbf72d420214c98191b23d0be6704591ea515fdf8019012fb5f9239ff
    spec:
      serviceAccountName: local-storage-admin
      nodeSelector:
        kubernetes.io/os: linux
      containers:
        - name: provisioner
          image: k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0
          imagePullPolicy: Always
          securityContext:
            privileged: true
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0
          ports:
          - name: metrics
            containerPort: 8080
          volumeMounts:
            - name: provisioner-config
              mountPath: /etc/provisioner/config
              readOnly: true
            - name: provisioner-dev
              mountPath: /dev
            - name: fast-disks
              mountPath: /hdd
              mountPropagation: HostToContainer
      volumes:
        - name: provisioner-config
          configMap:
            name: localpv-local-volume-static-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: /dev
        - name: fast-disks
          hostPath:
            path: /hdd
---
# Source: local-volume-static-provisioner/templates/daemonset_windows.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: localpv-local-volume-static-provisioner-win
  namespace: local-pv
  labels:
    helm.sh/chart: local-volume-static-provisioner-1.0.0
    app.kubernetes.io/name: local-volume-static-provisioner
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/instance: localpv
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: local-volume-static-provisioner
      app.kubernetes.io/instance: localpv
  template:
    metadata:
      labels:
        app.kubernetes.io/name: local-volume-static-provisioner
        app.kubernetes.io/instance: localpv
      annotations:
        checksum/config: d64a1ddfbf72d420214c98191b23d0be6704591ea515fdf8019012fb5f9239ff
    spec:
      serviceAccountName: local-storage-admin
      nodeSelector:
        kubernetes.io/os: windows
      tolerations:
        # an empty key operator Exists matches all keys, values and effects
        # which meants that this will tolerate everything
        - operator: "Exists"
      containers:
        - name: provisioner
          image: k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0
          imagePullPolicy: Always
          env:
          - name: MY_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: MY_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: JOB_CONTAINER_IMAGE
            value: k8s.gcr.io/sig-storage/local-volume-provisioner:v2.4.0
          ports:
          - name: metrics
            containerPort: 8080
          volumeMounts:
            - name: provisioner-config
              mountPath: /etc/provisioner/config
              readOnly: true
            - name: provisioner-dev
              mountPath: /dev
            - name: fast-disks
              mountPath: /hdd
              mountPropagation: HostToContainer
            - name: csi-proxy-volume-v1
              mountPath: \\.\pipe\csi-proxy-volume-v1
            - name: csi-proxy-filesystem-v1
              mountPath: \\.\pipe\csi-proxy-filesystem-v1
            # these csi-proxy paths are still included for compatibility, they're used
            # only if the node has still the beta version of the CSI proxy
            - name: csi-proxy-volume-v1beta2
              mountPath: \\.\pipe\csi-proxy-volume-v1beta2
            - name: csi-proxy-filesystem-v1beta2
              mountPath: \\.\pipe\csi-proxy-filesystem-v1beta2
      volumes:
        - name: csi-proxy-volume-v1
          hostPath:
            path: \\.\pipe\csi-proxy-volume-v1
            type: ""
        - name: csi-proxy-filesystem-v1
          hostPath:
            path: \\.\pipe\csi-proxy-filesystem-v1
            type: ""
        # these csi-proxy paths are still included for compatibility, they're used
        # only if the node has still the beta version of the CSI proxy
        - name: csi-proxy-volume-v1beta2
          hostPath:
            path: \\.\pipe\csi-proxy-volume-v1beta2
            type: ""
        - name: csi-proxy-filesystem-v1beta2
          hostPath:
            path: \\.\pipe\csi-proxy-filesystem-v1beta2
            type: ""
        - name: provisioner-config
          configMap:
            name: localpv-local-volume-static-provisioner-config
        - name: provisioner-dev
          hostPath:
            path: "C:\\dev"
            # If nothing exists at the given path, an empty directory will be
            # created there as needed with permission set to 0755,
            # having the same group and ownership with Kubelet.
            type: DirectoryOrCreate
        - name: fast-disks
          hostPath:
            path: /hdd
